### ISSUE TITLE
plugin not working for me

### ISSUE THREAD

**Issue by samuelrs** [Pollenizer/CakePHP-GeoIP-Plugin#2]
hello,
I'm trying to use the plugin, and following the tutorial.
  But not working.
  I did everything correctly to step 4.
  In part of usage in a controller, I added:

function index() {
      App::uses('GeoIpLocation', 'GeoIp.Model');
      $GeoIpLocation = new GeoIpLocation();
      $ipAddr = CakeRequest::clientIp(false);
      $location = $GeoIpLocation->find($ipAddr); 
      print_r($location);die();
}
but is not showing anything.
  What do am I doing wrong?

**Comment by sime** [comment]
If your IP is 127.0.0.1 the find will return an empty array.

Try passing a real IP such as 8.8.8.8 (Google DNS server)

On Fri, Jul 5, 2013 at 6:14 AM, samuelrs notifications@github.com wrote:

> hello,
> I'm trying to use the plugin, and following the tutorial.
> But not working.
> I did everything correctly to step 4.
> In part of usage in a controller, I added:
> 
> function index() {
> App::uses('GeoIpLocation', 'GeoIp.Model');
> $GeoIpLocation = new GeoIpLocation();
> $ipAddr = CakeRequest::clientIp(false);
> $location = $GeoIpLocation->find($ipAddr);
> print_r($location);die();
> }
> but is not showing anything.
> What do am I doing wrong?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Pollenizer/CakePHP-GeoIP-Plugin/issues/2
> .

## 

Simon Males

**Comment by samuelrs** [comment]
First thank you for answering!

  I did some more tests, and the function that returns the IP, it always is returning :: 1
  But would not have to return the ip of my machine?

  I tested adding the ip manually, and the plugin worked correctly. The problem is "CakeRequest :: clientIp (false);"

**Comment by samuelrs** [comment]
I put an example in an online host, and both the ip and the plugin worked correctly.

  I appreciate the help, and I suggest that you add a note, that when tested on localhost, this example is not functional.

thank you
